# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14.16.0

pipelines:
  branches:
    master:
      - step:
          name: 'Build and Deploy'
          caches:
            - node
          deployment: production
          artifacts:
            - dist/**
          script:
            - npm install
            - npm run build:prod
            - pipe: atlassian/firebase-deploy:1.1.0
              variables:
                FIREBASE_TOKEN: "1//0gQw8mBXBrbGsCgYIARAAGBASNwF-L9IrobPac0uimdCr9EG0Y9pmvY3RbxOUpgzzvuXWe96epOIQqGdXP-LY4g5yoCq2995n70I"



