# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14.16.0

pipelines:
  branches:
    master:
      - step:
          name: 'Build and Deploy'
          caches:
            - node
          deployment: production
          artifacts:
            - dist/**
          script:
            - npm install -g firebase-tools@8.12
            - npm install
            - npm run build
            - firebase use staging
            - firebase deploy --only hosting:production --token $FIREBASE_TOKEN
    release/*:
      - step:
          name: 'Build and Deploy'
          caches:
            - node
          deployment: production
          artifacts:
            - dist/**
          script:
            - npm install -g firebase-tools@8.12
            - npm install
            - npm run build
            - firebase use staging
            - firebase deploy --only hosting:staging --token $FIREBASE_TOKEN
