# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14.16.0

pipelines:
  default:
    - step:
        name: 'Build and Deploy'
        script:
          - npm install
          - npm run build:prod
          - firebase deploy --token=$FIREBASE_TOKEN --project project-name-firebase --non-interactive

