pipelines:
  default:
    - step:
        name: 'Build and Deploy'
        deployment: production
        script:
          - npm install
          - npm run build:prod
          - pipe: atlassian/firebase-deploy:1.1.0
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN