# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14.16.0

pipelines:
  branches:
    master:
      - step:
          name: 'Build and Deploy'
          caches:
            - node
          deployment: production
          artifacts:
            - dist/**
          script:
            - npm install
            - npm run build:prod
            - firebase use default
            - pipe: atlassian/firebase-deploy:1.1.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
    release:
      - step:
          name: 'Build and Deploy'
          caches:
            - node
          deployment: staging
          artifacts:
            - dist/**
          script:
            - npm install
            - npm run build
            - firebase use staging
            - pipe: atlassian/firebase-deploy:1.1.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN_INIT
